name: camera_module
services:
  camera_module:
    container_name: camera_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:${PROJECT_VERSION}
        - ${IMAGE}:dev
    command: python camera_module/src/camera_rest_node.py --port 2000
    privileged: true
    env_file: .env
    volumes:
      - ${DEVICE}:/dev/video0
      - ./src:/home/app/camera_module/src
      - ./tests:/home/app/camera_module/tests
    ports:
      - 2000:2000
